services:
  - type: web
    name: student-tracker
    env: java
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/studentTracker-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: 17
